name: Create NuGet Package Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x" # Update to the desired .NET Core version

      - name: Build and test
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg
      - name: Get short SHA
        id: get-short-sha
        run: |
          id=$(echo ${{github.sha}} | cut -c 1-7)
          echo "::set-output name=id::$id"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.get-short-sha.outputs.id }}
          release_name: Release ${{ steps.get-short-sha.outputs.id  }}
          body: |
            Release created automatically from commit ${{ steps.get-short-sha.outputs.id  }}.
          draft: false
          prerelease: false

      - name: Download NuGet package artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
          path: ./downloaded-artifacts

      - name: Publish NuGet package
        run: dotnet nuget push ./downloaded-artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
